# Generated by Django 5.2.4 on 2025-07-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='Caracteristica_Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('altura', models.IntegerField(verbose_name='Altura(centímetros)')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('genero', models.CharField(max_length=15, verbose_name='Gênero')),
                ('nivel_atividade', models.CharField(max_length=10, verbose_name='Nível de atividade')),
                ('objetivo', models.CharField(max_length=50, verbose_name='Objetivo')),
                ('detalhamento', models.CharField(max_length=100, verbose_name='Detalhamento')),
            ],
            options={
                'verbose_name': 'Caracteristica_Objetivo',
                'verbose_name_plural': 'Caracteristica_Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_consumida', models.IntegerField(verbose_name='Calorias consumidas')),
                ('cal_gasta', models.IntegerField(verbose_name='Calorias gastas')),
                ('proteina', models.IntegerField(verbose_name='Proteinas consumidas')),
                ('gordura', models.IntegerField(verbose_name='Gorduras consumidas')),
                ('peso_perdido', models.IntegerField(verbose_name='Peso Perdido')),
                ('peso_ganho', models.IntegerField(verbose_name='Peso ganho')),
            ],
            options={
                'verbose_name': 'Progresso',
                'verbose_name_plural': 'Progressos',
            },
        ),
        migrations.CreateModel(
            name='Dieta_Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dite_tipo', models.CharField(max_length=50, verbose_name='Tipo de dieta')),
                ('Caracteristica_Objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caracteristica_objetivo', verbose_name='Característica e objetivo')),
            ],
            options={
                'verbose_name': 'Dieta_Objetivo',
                'verbose_name_plural': 'Dietas_Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Filtrar_Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(max_length=15, verbose_name='Dificuldade')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('Caracteristica_Objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caracteristica_objetivo', verbose_name='Característica e objetivo')),
            ],
            options={
                'verbose_name': 'Filtrar_Atividade',
                'verbose_name_plural': 'Filtrar_Atividades',
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('som', models.CharField(max_length=50, verbose_name='Som')),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agenda', verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('nome_perfil', models.CharField(max_length=50, verbose_name='Nome de perfil')),
                ('recado', models.CharField(max_length=50, verbose_name='Deixe um recado')),
                ('Caracteristica_Objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caracteristica_objetivo', verbose_name='Características e objetivo')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Plano_Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino_ideal', models.CharField(max_length=50, verbose_name='Treino ideal')),
                ('Caracteristica_Objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caracteristica_objetivo', verbose_name='Característica e objetivo')),
            ],
            options={
                'verbose_name': 'Plano_Atividade',
                'verbose_name_plural': 'Planos_Atividades',
            },
        ),
    ]
