# Generated by Django 5.2.4 on 2025-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica_objetivo',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso'),
        ),
    ]
