# Generated by Django 5.2.4 on 2025-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_caracteristica_objetivo_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta_objetivo',
            name='dite_tipo',
            field=models.CharField(max_length=150, verbose_name='Tipo de dieta'),
        ),
    ]
