# Generated by Django 5.2.4 on 2025-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dieta_objetivo_dite_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica_objetivo',
            options={'verbose_name': 'Caracteristica_Objetivo', 'verbose_name_plural': 'Caracteristicas_Objetivos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='filtrar_atividade',
            name='tipo',
            field=models.CharField(max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='plano_atividade',
            name='treino_ideal',
            field=models.CharField(max_length=150, verbose_name='Treino ideal'),
        ),
    ]
