# Generated by Django 5.2.4 on 2025-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_caracteristica_objetivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='cal_consumida',
            field=models.IntegerField(verbose_name='Calorias consumidas no dia (kcal)'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='cal_gasta',
            field=models.IntegerField(verbose_name='Calorias gastas no dia (kcal)'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='gordura',
            field=models.IntegerField(verbose_name='Gorduras consumidas no dia (g)'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='peso_ganho',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso ganho no total(kg)'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='peso_perdido',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Perdido no total(kg)'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='proteina',
            field=models.IntegerField(verbose_name='Proteinas consumidas no dia (g)'),
        ),
    ]
