# Generated by Django 5.2.4 on 2025-07-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_progresso_cal_consumida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='Pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
            preserve_default=False,
        ),
    ]
