# Generated by Django 5.2.1 on 2025-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_progresso_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do exercício')),
                ('dificuldade', models.CharField(max_length=15, verbose_name='Dificuldade')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do exercício')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
    ]
